name: alquran_alkarim
description: A new Quran application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:


  # api wrapper
  alquran_wrapper:
    git:
      url: https://github.com/maxzod/alquran_wrapper.git
      ref: master
  # playing quran audio
  audioplayers: ^0.17.0
  # state management
  provider: ^4.3.3
  # navigation
  auto_route: ^1.0.0-beta.7
  # for offline support
  # sqflite: ^1.3.2+2
  # caching
  shared_preferences: ^0.5.12+4
  # fonts
  google_fonts:
  # get user location
  location: ^3.2.4
  # cache images
  # cached_network_image: ^2.5.0
  # share aya
  share: ^0.6.5+4
  # progress indicators
  # flutter_spinkit: ^4.1.2+1
  # icons
  font_awesome_flutter: ^8.11.0
  # introduction screen
  flutter_swiper: ^1.1.6
  intro_slider: ^2.3.3
  # localization
  easy_localization:
  # for web layout support
  responsive_builder: ^0.3.0
  # bottom nav bar
  google_nav_bar: ^3.2.0
  hive:
  hive_flutter:
  path_provider:
  native_pdf_view:
  advance_pdf_viewer:
  scroll_to_index:
  lottie:
  flutter_spinkit:
  fluttertoast:
  assets_audio_player:
  geolocator:


dev_dependencies:
  hive_generator:
  # see how ui looks on different screen sizes
  device_preview: ^0.5.5
  # code generation for auto_route
  auto_route_generator:
  # dart code generator
  build_runner:
  share:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/langs/ar-DZ.json
    - assets/langs/en-US.json
    - assets/images/
    - assets/quran-images/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
